apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mg-external-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: mg-secretstore
    kind: SecretStore
  target:
    name: mg-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: mg-k8s-secret-key
      remoteRef:
        key: dev/mg-ui/test1
        property: secret_row_1_key
