apiVersion: apps/v1
kind: Deployment
metadata:
  name: mg-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mg-ui
  template:
    metadata:
      labels:
        app: mg-ui
    spec:
      serviceAccountName: mg-service-account
      containers:
      - image: mischl01/mgnginx1:0.3
        name: mg-ui
	resources:
	  limits:
	    cpu: 1
	    memory: 1Gi
	  requests:
	    cpu: 2
	    memory: 2Gi
        ports:
        - containerPort: 80

