apiVersion: apps/v1
kind: Deployment
metadata:
  name: mg-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mg-ui
  template:
    metadata:
      labels:
        app: mg-ui
    spec:
      serviceAccountName: mg-service-account
      containers:
      - image: mischl01/mgnginx1:0.3
        name: mg-ui
        resources:
          limits:
            cpu: 0.8m
            memory: 800Mi
          requests:
            cpu: 0.9m
            memory: 900Mi
        ports:
        - containerPort: 80

