apiVersion: apps/v1
kind: Deployment
metadata:
  name: mg-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mg-ui
  template:
    metadata:
      labels:
        app: mg-ui
    spec:
      serviceAccountName: mg-service-account
      containers:
      - image: mischl01/mgnginx1:0.3
        name: mg-ui
        command: ["sh", "-c"]
        args: ["echo test123"]
        env:
        - name: MG_K8S_SECRET
          valueFrom:
            secretKeyRef:
              name: mg-k8s-secret
              key: mg-k8s-secret-key
        ports:
        - containerPort: 80

