apiVersion: apps/v1
kind: Deployment
metadata:
  name: mg-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mg-ui
  template:
    metadata:
      labels:
        app: mg-ui
    spec:
      serviceAccountName: mg-service-account
      containers:
      - image: mischl01/mgnginx1:0.3
        name: mg-ui
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
        ports:
        - containerPort: 80

